### ISSUE TITLE
Utilize controllerAs syntax

### ISSUE THREAD

**Issue by JakePartusch** [improving-minnesota/angular-timesheet#68]
Once Angular and UI router are upgraded, utilize 'controllerAs' syntax rather than $scope:

https://github.com/johnpapa/angular-styleguide#controllers

**Comment by tmartensen** [comment]
Note that adding `controllerAs` to ui-router code would look something like this, where you would have to go into the template and add the controller name to your variables:

```
$stateProvider.state('contacts', {
  template: '<h1>{{contact.title}}</h1>',
  controller: function(){
    this.title = 'My Contacts';
  },
  controllerAs: 'contact'
})
```

**Comment by tmartensen** [comment]
For the purposes of this training class, I think that we should probably use the 'controllerAs with vm' syntax' in order to avoid having to deal with issues stemming from using `this`. Details here: https://github.com/johnpapa/angular-styleguide#controlleras-with-vm

**Comment by hartstinger** [comment]
After some discussion with Travis, to make things a little more readable and avoid confusion, the ui-router 'controllerAs' would carry the same controller name. e.g. controller: 'ProjectCtrl', controllerAs: 'projectCtrl'.
This improves readability in nested controller scenarios. The controller will still use var vm = this.

**Comment by tmartensen** [comment]
Another thing I thought of: it may be really helpful to go through the lab directions when you're working through updating all the controllers. The labs can be found in the `angular-training` project: 
https://github.com/objectpartners/angular-training/tree/develop/labs

**Comment by tmartensen** [comment]
I think all this work is now complete. Closing...
